### ISSUE TITLE
unknown tag !<!ImportValue>

### ISSUE THREAD

**Issue by aarongorka** [yyolk/cloudformation-js-yaml-schema#13]
With the tests in https://github.com/yyolk/cloudformation-js-yaml-schema/pull/12 (which is valid CloudFormation), I get this error upon running `npm test`:

```> cloudformation-js-yaml-schema@0.3.3 test /srv/app
> node test.js


/srv/app/node_modules/js-yaml/lib/js-yaml/loader.js:171
  throw generateError(state, message);
  ^
YAMLException: unknown tag !<!ImportValue> at line 31, column 1:

    ^
    at generateError (/srv/app/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/srv/app/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at composeNode (/srv/app/node_modules/js-yaml/lib/js-yaml/loader.js:1401:7)
    at readBlockMapping (/srv/app/node_modules/js-yaml/lib/js-yaml/loader.js:1062:11)
    at composeNode (/srv/app/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readBlockMapping (/srv/app/node_modules/js-yaml/lib/js-yaml/loader.js:1062:11)
    at composeNode (/srv/app/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readBlockMapping (/srv/app/node_modules/js-yaml/lib/js-yaml/loader.js:1062:11)
    at composeNode (/srv/app/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readDocument (/srv/app/node_modules/js-yaml/lib/js-yaml/loader.js:1492:3)
```

**Comment by yyolk** [comment]
Closed with #14
